### ISSUE TITLE
Adding a sidebar toggle button so it's not always showing.

### ISSUE THREAD

**Issue by itsmais** [time-it-app/time-it-app#3]
A burger button would be nice in order to toggle the sidebar so it doesn't show all the times.

**Comment by itsmais** [comment]
@nguyenhung15913 done. Thank you so much!

**Comment by nguyenhung15913** [comment]
Hi @itsmais I cloned the project and <code>npm install</code>. But when I start the command <code>npm run dev</code>. I got an error in the screenshot below. Can you explain it to me thanks.
![image](https://user-images.githubusercontent.com/69558780/137397401-e745e136-656a-4a1b-867f-701f66ee698b.png)

**Comment by nguyenhung15913** [comment]
Mine is v14.15.1 and I am using Windows too

**Comment by itsmais** [comment]
Forgot to ask, what npm version are you using? here it's `7.24.2`.

**Comment by itsmais** [comment]
Yes, I saw that too and I'm wondering what else could be causing this.

**Comment by nguyenhung15913** [comment]
yeah for sure. I joined
